trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build & Test
    jobs:
      - job: BuildJob
        steps:
          - checkout: self
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11'
            displayName: 'Use Python 3.11'
          - script: |
              pip install -r projet-9-cicd-devops/app/requirements.txt
              pytest projet-9-cicd-devops/app/tests/ -v
            displayName: 'Install dependencies & Run tests'

  - stage: Deploy
    displayName: Deploy to Azure App Service
    dependsOn: Build
    jobs:
      - job: DeployJob
        steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Flask app'
            inputs:
              azureSubscription: 'azure-service-connection'
              appType: 'webAppLinux'
              appName: 'webapp-cicd-projet9'
              package: '$(System.DefaultWorkingDirectory)/projet-9-cicd-devops/app'
              runtimeStack: 'PYTHON|3.11'
              startUpCommand: 'gunicorn --bind=0.0.0.0 app:app'
